services:
  - type: web
    name: company-website
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn authentication.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: authentication.settings
      - key: DATABASE_URL
        sync: false
    autoDeploy: true
