# Generated by Django 5.1.1 on 2024-10-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
