# Generated by Django 5.1.1 on 2024-10-18 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_employer_otp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OTP',
            new_name='OtpToken',
        ),
    ]
