# Generated by Django 5.1.1 on 2024-10-18 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_otp_otptoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='email',
        ),
    ]
