# Generated by Django 5.1.1 on 2024-10-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_employer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='email',
            field=models.CharField(max_length=225),
        ),
    ]
