# Generated by Django 5.1.1 on 2024-10-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_otptoken_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talent',
            name='email',
        ),
        migrations.AddField(
            model_name='talent',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
