# Generated by Django 5.1.2 on 2024-11-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='cpmpany_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
