# Generated by Django 5.1.2 on 2024-11-12 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_employer_cpmpany_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer',
            old_name='cpmpany_email',
            new_name='company_email',
        ),
    ]
